- name: Python dependencies
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-dev
      - libmysqlclient-dev
    state: present
  tags: task1 

- name: Install mysqlclient via pip 
  ansible.builtin.pip:
    name: mysqlclient
    state: present
    extra_args: --break-system-packages # "Force" ignorar error PEP 668 externally managed
  tags: task2
